### ISSUE TITLE
analysis_options.yaml doesn't respect the working-directory

### ISSUE THREAD

**Issue by dangilbert** [ValentinVignal/action-dart-analyze#2]
Hi,

My flutter project is in a sub-directory of the root and has its analysis_options.yaml file in there, but I have had to symlink it to the project root to make it work.

It looks like it isn't respecting the working-directory argument

**Comment by ValentinVignal** [comment]
Thank you for the issue. Sorry for the delay, I have been quite busy this week. I see you already submitted a PR 👍
I'll take a look this week.

**Comment by ValentinVignal** [comment]
@dangilbert This should be fixed in the version `v0.12`.

I let you reopen the issue if it is not the case

**Comment by Bhupesh-V** [comment]
@ValentinVignal I don't know if this is a related issue but the action is not able to find the `analysis_option.yaml` file

```
Run ValentinVignal/action-dart-analyze@v0.12
  with:
    fail-on: warning
    working-directory: ./
    token: ***
    check-renamed-files: false
    emojis: true
    format: true
  env:
    JAVA_HOME_12.0.2_x64: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /opt/hostedtoolcache/jdk/12.0.2/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/2.8.0-stable/x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/2.8.0-stable/x64/.pub-cache
Could not load analysis_options.yaml:
Error: ENOENT: no such file or directory, open '/home/runner/work/repooo/analysis_options.yaml'
 Analyze dart code
 Analyze formatting
Dart Analyzer found 0 issue
- 0 error.
- 0 warning.
- 0 info log.
- 0 formatting issue
```


this is my workflow

```yaml
jobs:
  build:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: pre-release/0.3.4
          submodules: recursive
          token: ${{ secrets.CLONE_SUBMODULE_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Setup dependencies
        run: sh flutter_super_get.sh
      - name: Analyze Dart
        uses: ValentinVignal/action-dart-analyze@v0.12
        with:
          fail-on: 'warning'
      #   uses: zgosalvez/github-actions-analyze-dart@v1.6.1

```
